language: python

python: 3.7

env:
  - codacy = CODACY

install:
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover

after_success:
  - coverage xml
  - CODACY_PROJECT_TOKEN = codacy
  - python-codacy-coverage -r coverage.xml

notifications:
  email: false
