language: python

python: 3.7

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - python -m unittest github.test.test_web_scraping

after_success:
  - codecov

notifications:
  email: false
