language: python

python: 3.7

install:
  - pip install -r requirements.txt
  - pip install flake8

script:
  - python -m unittest github.test.test_web_scraping
  - flake8

notifications:
  email: false
